go:
    version: 1.12.6
    cgo: false
repository:
    path: github.com/jgrancell/vault_exporter
build:
    binaries:
        - name: vault_exporter
    flags: -a -tags -installsuffix
    ldflags: |
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
